# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('marvel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('marvel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('variant_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('url', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('characters', models.ManyToManyField(blank=True, to='marvel.Character')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('marvel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('suffix', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=600, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('marvel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('characters', models.ManyToManyField(blank=True, to='marvel.Character')),
                ('comics', models.ManyToManyField(blank=True, to='marvel.Comic')),
                ('creators', models.ManyToManyField(blank=True, to='marvel.Creator')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MarvelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=800)),
                ('extension', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('path',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=200)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvel.Comic')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marvel.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('marvel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('characters', models.ManyToManyField(blank=True, to='marvel.Character')),
                ('comics', models.ManyToManyField(blank=True, to='marvel.Comic')),
                ('creators', models.ManyToManyField(blank=True, to='marvel.Creator')),
                ('events', models.ManyToManyField(blank=True, to='marvel.Event')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marvel.MarvelImage')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='marvelimage',
            unique_together=set([('path', 'extension')]),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marvel.MarvelImage'),
        ),
        migrations.AddField(
            model_name='event',
            name='series_list',
            field=models.ManyToManyField(blank=True, to='marvel.Series'),
        ),
        migrations.AddField(
            model_name='creator',
            name='comics',
            field=models.ManyToManyField(blank=True, through='marvel.Role', to='marvel.Comic'),
        ),
        migrations.AddField(
            model_name='creator',
            name='events',
            field=models.ManyToManyField(blank=True, to='marvel.Event'),
        ),
        migrations.AddField(
            model_name='creator',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marvel.MarvelImage'),
        ),
        migrations.AddField(
            model_name='creator',
            name='series_list',
            field=models.ManyToManyField(blank=True, to='marvel.Series'),
        ),
        migrations.AddField(
            model_name='comic',
            name='creators',
            field=models.ManyToManyField(blank=True, through='marvel.Role', to='marvel.Creator'),
        ),
        migrations.AddField(
            model_name='comic',
            name='events',
            field=models.ManyToManyField(blank=True, to='marvel.Event'),
        ),
        migrations.AddField(
            model_name='comic',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marvel.MarvelImage'),
        ),
        migrations.AddField(
            model_name='comic',
            name='series_list',
            field=models.ManyToManyField(blank=True, to='marvel.Series'),
        ),
        migrations.AddField(
            model_name='character',
            name='comics',
            field=models.ManyToManyField(blank=True, to='marvel.Comic'),
        ),
        migrations.AddField(
            model_name='character',
            name='events',
            field=models.ManyToManyField(blank=True, to='marvel.Event'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marvel.MarvelImage'),
        ),
        migrations.AddField(
            model_name='character',
            name='series_list',
            field=models.ManyToManyField(blank=True, to='marvel.Series'),
        ),
    ]
