# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='creator',
            name='full_name',
            field=models.CharField(db_index=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
