# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0002_auto_20161217_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='issue_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
